name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.21
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.2.2
  meta: ">=1.10.0 <1.17.0"
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  build_runner: ^2.1.11
  json_serializable: ^6.9.0
  coverage: ^1.0.0
